CREATE TABLE [dbo].[FARMER]
(
	[FARMER_ID] VARCHAR(50) NOT NULL, 
    [FARMER_NAME] VARCHAR(20) NOT NULL, 
    [FARMER_SURNAME] VARCHAR(20) NOT NULL, 
    [FARMER_DOB] DATE NULL, 
    [FARMER_CELL] VARCHAR(10) NULL, 
    [FARMER_EMAIL] VARCHAR(50) NULL, 
    [USERNAME] VARCHAR(10) NOT NULL, 

	CONSTRAINT FARMER_PK PRIMARY KEY (FARMER_ID),
	CONSTRAINT FARMER_FK FOREIGN KEY (USERNAME) REFERENCES USERCREDENTIAL (USERNAME)
)
