INSERT INTO USERCREDENTIAL (USERNAME, P_PASSWORD)
VALUES ('Koos123','Admin1')

INSERT INTO FARMER(FARMER_ID, FARMER_NAME, FARMER_SURNAME, FARMER_DOB , FARMER_CELL, FARMER_EMAIL, USERNAME)
VALUES (101, 'John', 'Wick', '2023/05/14', '0823098927', 'gg@gmail.com', 'Koos123')

dELETE FROM USERCREDENTIAL WHERE USERNAME = 'Koos123'

Delete from FARMER where FARMER_ID = 101

Select * from FARMER

Select * from USERCREDENTIAL