Select * from FARMER;

SELECT F.USERNAME FROM FARMER F;

select * from PRODUCT;

select * from FARMPROD;

DELETE FROM FARMPROD  WHERE PRODUCT_CODE = 'XYZ234';

DELETE FROM PRODUCT WHERE PRODUCT_CODE = 'XYZ234';